name: Build and Release macOS App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
        
    - name: Install dependencies
      run: |
        # Install create-dmg for DMG creation
        brew install create-dmg
        
    - name: Setup signing certificates
      env:
        DEVELOPER_ID_APPLICATION: ${{ secrets.DEVELOPER_ID_APPLICATION }}
        DEVELOPER_ID_APPLICATION_PASSWORD: ${{ secrets.DEVELOPER_ID_APPLICATION_PASSWORD }}
        DEVELOPER_ID_INSTALLER: ${{ secrets.DEVELOPER_ID_INSTALLER }}
        DEVELOPER_ID_INSTALLER_PASSWORD: ${{ secrets.DEVELOPER_ID_INSTALLER_PASSWORD }}
      run: |
        # Create temporary keychain
        security create-keychain -p "$RUNNER_TEMP" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$RUNNER_TEMP" build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
        
        # Import Developer ID Application certificate
        echo "$DEVELOPER_ID_APPLICATION" | base64 --decode > cert.p12
        security import cert.p12 -k build.keychain -P "$DEVELOPER_ID_APPLICATION_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
        rm cert.p12
        
        # Import Developer ID Installer certificate (for DMG signing)
        echo "$DEVELOPER_ID_INSTALLER" | base64 --decode > installer.p12
        security import installer.p12 -k build.keychain -P "$DEVELOPER_ID_INSTALLER_PASSWORD" -T /usr/bin/productbuild -T /usr/bin/security
        rm installer.p12
        
        # Allow codesign to access the keychain
        security set-key-partition-list -S apple-tool:,apple: -s -k "$RUNNER_TEMP" build.keychain
        
    - name: Build Swift package
      run: |
        swift build --configuration release --arch arm64 --arch x86_64
        
    - name: Create app bundle structure
      run: |
        APP_NAME="ScreenshotForChat"
        APP_BUNDLE="$APP_NAME.app"
        
        # Create bundle directories
        mkdir -p "$APP_BUNDLE/Contents/MacOS"
        mkdir -p "$APP_BUNDLE/Contents/Resources"
        
        # Copy executable
        cp .build/apple/Products/Release/$APP_NAME "$APP_BUNDLE/Contents/MacOS/"
        
        # Copy Info.plist (create from template if doesn't exist)
        if [ -f "Info.plist" ]; then
          cp Info.plist "$APP_BUNDLE/Contents/"
        else
          cat > "$APP_BUNDLE/Contents/Info.plist" << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDisplayName</key>
            <string>Screenshot for Chat</string>
            <key>CFBundleExecutable</key>
            <string>ScreenshotForChat</string>
            <key>CFBundleIdentifier</key>
            <string>com.fsck.screenshotforchat</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>Screenshot for Chat</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>${{ github.event.inputs.version || github.ref_name }}</string>
            <key>CFBundleVersion</key>
            <string>${{ github.run_number }}</string>
            <key>CFBundleIconFile</key>
            <string>ScreenshotForChat</string>
            <key>LSMinimumSystemVersion</key>
            <string>14.0</string>
            <key>LSUIElement</key>
            <true/>
            <key>NSHumanReadableCopyright</key>
            <string>Copyright 2025 Jesse Vincent</string>
        </dict>
        </plist>
        EOF
        fi
        
        # Copy resources if they exist
        if [ -d "Resources" ]; then
          cp -R Resources/* "$APP_BUNDLE/Contents/Resources/" 2>/dev/null || true
        fi
        
        # Copy icon if it exists
        if [ -f "Resources/ScreenshotForChat.icns" ]; then
          cp "Resources/ScreenshotForChat.icns" "$APP_BUNDLE/Contents/Resources/"
        fi
        
    - name: Sign app bundle
      env:
        DEVELOPER_ID_NAME: ${{ secrets.DEVELOPER_ID_NAME }}
      run: |
        APP_BUNDLE="ScreenshotForChat.app"
        
        # Sign all executables in the bundle
        find "$APP_BUNDLE" -type f -perm +111 -exec codesign --force --options runtime --sign "$DEVELOPER_ID_NAME" {} \;
        
        # Sign the app bundle itself
        codesign --force --options runtime --sign "$DEVELOPER_ID_NAME" "$APP_BUNDLE"
        
        # Verify signature
        codesign --verify --verbose "$APP_BUNDLE"
        spctl --assess --verbose "$APP_BUNDLE"
        
    - name: Create DMG
      run: |
        APP_NAME="ScreenshotForChat"
        VERSION="${{ github.event.inputs.version || github.ref_name }}"
        DMG_NAME="${APP_NAME}-${VERSION}.dmg"
        
        create-dmg \
          --volname "$APP_NAME" \
          --volicon "Resources/ScreenshotForChat.icns" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "$APP_NAME.app" 200 190 \
          --hide-extension "$APP_NAME.app" \
          --app-drop-link 600 185 \
          --hdiutil-quiet \
          "$DMG_NAME" \
          "$APP_NAME.app" || true
          
        # If create-dmg fails, create a simple DMG
        if [ ! -f "$DMG_NAME" ]; then
          echo "create-dmg failed, creating simple DMG"
          hdiutil create -srcfolder "$APP_NAME.app" -volname "$APP_NAME" "$DMG_NAME"
        fi
        
    - name: Sign DMG
      env:
        DEVELOPER_ID_NAME: ${{ secrets.DEVELOPER_ID_NAME }}
      run: |
        VERSION="${{ github.event.inputs.version || github.ref_name }}"
        DMG_NAME="ScreenshotForChat-${VERSION}.dmg"
        
        # Sign the DMG
        codesign --force --sign "$DEVELOPER_ID_NAME" "$DMG_NAME"
        
        # Verify DMG signature
        codesign --verify --verbose "$DMG_NAME"
        
    - name: Notarize app
      env:  
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        VERSION="${{ github.event.inputs.version || github.ref_name }}"
        DMG_NAME="ScreenshotForChat-${VERSION}.dmg"
        
        # Submit for notarization
        xcrun notarytool submit "$DMG_NAME" \
          --apple-id "$APPLE_ID" \
          --password "$APPLE_ID_PASSWORD" \
          --team-id "$APPLE_TEAM_ID" \
          --wait
          
        # Staple the notarization
        xcrun stapler staple "$DMG_NAME"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ScreenshotForChat-${{ github.event.inputs.version || github.ref_name }}
        path: |
          ScreenshotForChat-*.dmg
          ScreenshotForChat.app
          
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ScreenshotForChat-*.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Cleanup keychain
      if: always()
      run: |
        security delete-keychain build.keychain || true